[versions]
java = "17"
kotlin = "2.2.0" # the highest version supported by the plugin at the moment

xemanticKotlinTest = "1.14.2"

kotlinDslPlugin = "6.2.0" # the highest version supported by gradle 9.1.0 at the moment
versionsPlugin = "0.53.0"
dokkaPlugin = "2.1.0"
jreleaserPlugin = "1.20.0"
binaryCompatibilityValidatorPlugin = "0.18.1"
xemanticConventionsPlugin = "0.4.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
xemantic-kotlin-test = { module = "com.xemantic.kotlin:xemantic-kotlin-test", version.ref = "xemanticKotlinTest" }

[plugins]
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDslPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidatorPlugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugin" }
power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
xemantic-conventions = { id = "com.xemantic.gradle.xemantic-conventions", version.ref = "xemanticConventionsPlugin" }
